version: '3.9'
services:
  my-cosme-library-mysql:
    image: 'mysql:8.0'
    container_name: my-cosme-library-mysql
    working_dir: /var/www/html
    volumes:
      - ./docker/database:/var/lib/mysql
      - ./docker/mysql-files:/var/lib/mysql-files
      - ./client:/var/www/html
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 8108:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  my-cosme-library-client:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.local
    container_name: my-cosme-library-client
    ports:
     - "8182:80"
    working_dir: /var/www/html
    volumes:
      - ./client:/var/www/html
    links:
      - my-cosme-library-mysql